mirageClub/app/cajas/models.py
from sqlalchemy import func
from sqlalchemy.sql.schema import ForeignKey
from app import db
import locale


class Ingreso(db.Model):
    Id = db.Column(db.Integer, primary_key=True)
    Id_socio = db.Column(db.Integer, ForeignKey('socio.Id'), nullable=True)
    Fecha = db.Column(db.Date, nullable=False)
    Monto = db.Column(db.Numeric(10, 2), default=0.00, nullable=False)
    Descripcion = db.Column(db.String(300), nullable=False)
    Eliminado = db.Column(db.Boolean, default=True, nullable=False)
    Fcarga = db.Column(db.Date, nullable=False)

    def __init__(self, Id_socio, Fecha, Monto, Descripcion):
        self.Id_socio = Id_socio
        self.Fecha = Fecha
        self.Monto = Monto
        self.Descripcion = Descripcion

    def get_all():
        return Ingreso.query.all()

    def get_active():
        return Ingreso.query.filter_by(Eliminado=1).all()

    def get_by_id(_id):
        return Ingreso.query.filter_by(Id=_id).one()
    
    def cerrar(self):
        self.Eliminado = 0
        db.session.commit()


class Egreso(db.Model):
    Id = db.Column(db.Integer, primary_key=True)
    Id_rubro = db.Column(db.Integer, ForeignKey('rubro.Id'))
    Fecha = db.Column(db.Date, nullable=False)
    Importe = db.Column(db.Numeric(10, 2), default=0.00, nullable=False)
    Descripcion = db.Column(db.String(200), nullable=False)
    Fcarga = db.Column(db.Date, nullable=False)

    def __init__(self, Id_rubro, Fecha, Importe, Descripcion):
        self.Id_rubro = Id_rubro
        self.Fecha = Fecha
        self.Importe = Importe
        self.Descripcion = Descripcion

    def get_all():
        return Egreso.query.all()

    def get_active():
        return Egreso.query.filter_by(Eliminado=1).all()

    def get_by_id(_id):
        return Egreso.query.filter_by(Id=_id).one()


class Rubro(db.Model):
    Id = db.Column(db.Integer, primary_key=True)
    Nombre = db.Column(db.String(200), nullable=False)
    Eliminado = db.Column(db.Boolean, default=True, nullable=False)

    def __init__(self, Nombre):
        self.Nombre = Nombre

    def get_all():
        return Rubro.query.all()

    def get_active():
        return Rubro.query.filter_by(Eliminado=1).all()

    def get_by_id(_id):
        return Rubro.query.filter_by(Id=_id).one()
    
    def eliminar(self):
        self.Eliminado = 0
        db.session.commit()

mirageClub/app/cajas/__init__.py
from flask import Blueprint

cajas_bp = Blueprint('cajas', __name__, template_folder='templates')

# NO BORRAR vvvv
from . import controllers

mirageClub/app/cajas/controllers.py
from flask import render_template, request, url_for, jsonify, flash, g, abort
import decimal
import pytz
from datetime import datetime
from werkzeug.utils import redirect
from app.deudas.models import Deuda
from app.personas.models import Persona
from app.socios.models import Socio
from app.pagos.models import Pago
from app.usuarios.decorator import auth_required
from .models import Ingreso, Egreso, Rubro
from .schemas import ingreso_schema, egreso_schema, rubro_schema
from app import db

from . import cajas_bp


@cajas_bp.route("/")
@auth_required
def index():
    pagos = Pago.get_all()
    deudas = Deuda.get_all()
    socio = Socio.get_all()
    persona = Persona.get_all()
    ingresos = Ingreso.get_all()
    egresos = Egreso.get_all()
    rubros = Rubro.get_all()
    return render_template('cajas.html', pagos=pagos, deudas=deudas, socios=socio, personas=persona, ingresos=ingresos, egresos=egresos, rubros=rubros)


@cajas_bp.route("/ingresos")  # INGRESOS
@auth_required
def ingresos():
    lista = Ingreso.get_all()
    socio = Socio.get_all()
    listasocio = Socio.get_active()
    persona = Persona.get_all()
    return render_template('ingresos.html', ingresos=lista, socios=socio, listasocio=listasocio, personas=persona)


@cajas_bp.route("/ingresos/add", methods=['POST'])
@auth_required
def ingresos_add():
    if request.method == 'POST':
        try:
            Id_socio = int(request.form['Id_socio'])
        except:
            Id_socio = None
        Fecha = request.form['Fecha']
        Monto = request.form['Monto']
        Descripcion = request.form['Descripcion']

        ingreso = Ingreso(Id_socio, Fecha, Monto, Descripcion)
        db.session.add(ingreso)
        db.session.commit()
        flash(f"Ingreso Registrado Correctamente {ingreso}", "success")
        return redirect(url_for('cajas.ingresos'))


@cajas_bp.route("/ingresos/modal_ver", methods=['POST'])
@auth_required
def ingresos_modal_ver():
    if request.method == 'POST':
        data = request.get_json()
        data = data[0]

        ingreso = ingreso_schema.dump(
            Ingreso.get_by_id(data['idIngreso']))
        return jsonify(ingreso), 200


@cajas_bp.route("/ingresos/edit", methods=['POST'])
@auth_required
def ingresos_edit():
    id = request.form['idIngreso']
    ingreso = Ingreso.get_by_id(id)
    ingreso.Descripcion = request.form['Descripcion']

    db.session.commit()
    flash(f"Ingreso Editado Correctamente {ingreso}", "info")
    return redirect(url_for('cajas.ingresos'))


@cajas_bp.route("/egresos")  # EGRESOS
@auth_required
def egresos():
    lista = Egreso.get_all()
    rubros = Rubro.get_all()
    listarubro = Rubro.get_active()
    return render_template('egresos.html', egresos=lista, rubros=rubros, listarubro=listarubro)


@cajas_bp.route("/egresos/add", methods=['POST'])
@auth_required
def egresos_add():
    if request.method == 'POST':
        Id_rubro = int(request.form['Id_rubro'])
        Fecha = request.form['Fecha']
        Importe = request.form['Importe']
        Descripcion = request.form['Descripcion']

        egreso = Egreso(Id_rubro, Fecha, Importe, Descripcion)
        db.session.add(egreso)
        db.session.commit()
        flash(f"Egreso Registrado Correctamente {egreso}", "success")
        return redirect(url_for('cajas.egresos'))


@cajas_bp.route("/egresos/modal_ver", methods=['POST'])
@auth_required
def egresos_modal_ver():
    if request.method == 'POST':
        data = request.get_json()
        data = data[0]
        egreso = egreso_schema.dump(
            Egreso.get_by_id(data['idEgreso']))
        return jsonify(egreso), 200


@cajas_bp.route("/egresos/edit", methods=['POST'])
@auth_required
def egresos_edit():
    id = request.form['idEgreso']
    egreso = Egreso.get_by_id(id)
    egreso.Descripcion = request.form['Descripcion']

    db.session.commit()
    flash(f"Egreso Editado Correctamente {egreso}", "info")
    return redirect(url_for('cajas.egresos'))


@cajas_bp.route("/egresos/rubros")  # RUBROS
@auth_required
def rubros():
    lista = Rubro.get_all()
    return render_template('rubros.html', rubros=lista)


@cajas_bp.route("/egresos/rubros/add", methods=['POST'])
@auth_required
def rubros_add():
    if request.method == 'POST':
        Nombre = request.form['Nombre']

        rubro = Rubro(Nombre)
        db.session.add(rubro)
        db.session.commit()
        flash(f"Rubro Registrado Correctamente {rubro}", "success")
        return redirect(url_for('cajas.rubros'))


@cajas_bp.route("/egresos/rubros/modal_ver", methods=['POST'])
@auth_required
def rubros_modal_ver():
    if request.method == 'POST':
        data = request.get_json()
        data = data[0]
        rubro = rubro_schema.dump(
            Rubro.get_by_id(data['idRubro']))
        return jsonify(rubro), 200


@cajas_bp.route("/egresos/rubros/edit", methods=['POST'])
@auth_required
def rubros_edit():
    id = request.form['idRubro']
    rubro = Rubro.get_by_id(id)
    rubro.Nombre = request.form['Nombre']

    db.session.commit()
    flash(f"Rubro Editado Correctamente {rubro}", "info")
    return redirect(url_for('cajas.rubros'))

mirageClub/app/cajas/templates/egresos.html
{% extends "base_template.html" %}

{% block title %}Egresos{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg">
        {%if g.user and g.user.Id_tipousuario == 1 %}
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modelNuevo">
            Cargar Nuevo Egreso
        </button>
        {%endif%}
    </div>

    <div class="col-md">
        <div class="btn-group float-right" role="group">
            <a class="btn btn-primary btn-lg mr-1 " href='{{ url_for("cajas.ingresos") }}'>
                Ingresos
            </a>
            <a class="btn btn-primary btn-lg" href='{{ url_for("cajas.rubros") }}'>
                Rubros
            </a>
        </div>
    </div>
</div>
<br>
<table style="width:100%" class="table table-dark table-hover table-bordered mt-3 display nowrap" id="myTable">
    <thead class="text-center">
        <th scope="col">Motivo</th>
        <th scope="col">Fecha</th>
        <th scope="col">Importe</th>
        <th scope="col">Descripcion</th>
        <th scope="col">Fecha de Carga</th>
    </thead>
    <tbody>
        {%for egreso in egresos %}
        <tr class="text-center text-dark table-secondary">
            {% for rubro in rubros%}
            {%if rubro.Id == egreso.Id_rubro%}
            <td class="text-left" onclick="boton_ver({{egreso.Id}})">{{rubro.Nombre}}</td>
            {%endif%}
            {%endfor%}
            <td onclick="boton_ver({{egreso.Id}})">{{egreso.Fecha.strftime('%Y-%m-%d')}}</td>
            <td onclick="boton_ver({{egreso.Id}})">{{egreso.Importe}}</td>
            <td onclick="boton_ver({{egreso.Id}})">{{egreso.Descripcion}}</td>
            <td onclick="boton_ver({{egreso.Id}})">{{egreso.Fcarga.strftime('%Y-%m-%d %H:%M:%S')}}</td>

            <!-- # MODAL BORRAR - CONFIRMACION ? -->
            <!-- # PAGINACION -->
        </tr>
        {% endfor %}
    </tbody>
</table>


<!-- Modal AGREGAR-->
<div class="modal fade" id="modelNuevo" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-md modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    Nuevo Egreso
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="submitAdd" action='{{ url_for("cajas.egresos_add") }}' method="post">
                    <div class="card">
                        <div class="card-body">
                            <label for="Id_rubro">Motivo</label>
                            <select class="form-control mb-2 col-md-8" name="Id_rubro" id="Id_rubro" required>
                                <option value="x">Seleccione un Rubro</option>
                                {%for rubro in listarubro%}
                                <option value="{{rubro.Id}}">{{rubro.Nombre}}</option>
                                {%endfor%}
                            </select>
                            <span id="spanAdd" class="input-group text-danger font-weight-bold"></span>
                            <label for="datetimepicker1">Fecha</label>
                            <div class="input-group mb-2 col-md-6">
                                <input type="text" class="form-control ml-n3" placeholder="YYYY-MM-DD"
                                    id="datetimepicker1" name="Fecha" required>
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                                </div>
                            </div>
                            <label for="Importe">Importe</label>
                            <input type="text" step="0.01" maxlength="11" class="form-control" name="Importe"
                                placeholder="Ingresar monto (0.00)" pattern="[0-9]{1,8}\.[0-9]{1,2}"
                                title="Usar decimales (0.00)" required>
                            <label for="Descripcion">Descripcion</label>
                            <input type="text" maxlength="300" class="form-control mb-2" name="Descripcion"
                                placeholder="Descripción del Ingreso" required>
                            <!-- max con moment -->
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-success" type="submit">
                            Guardar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<!-- Modal VER -->
<div class="modal fade" id="modal_ver" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-md modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Info</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- ID #?? // form.request['idActividad']-->
                <form id="submitVer" action='{{ url_for("cajas.egresos_edit") }}' method="post">
                    <!-- Recarga la pagina, AJAX? -->
                    <div class="card">
                        <div class="card-body">
                            <input type="text" name="idEgreso" id="idEgresoVer" style="display: none;">
                            <label for="Id_Rubro">Motivo</label>
                            <select class="form-control mb-2 col-md-8" name="Id_Rubro" id="Id_RubroVer" required
                                disabled>
                                <option value="x">Seleccione un Rubro</option>
                                {%for rubro in rubros%}
                                <option value="{{rubro.Id}}">{{rubro.Nombre}}</option>
                                {%endfor%}
                            </select>
                            <label for="Fecha">Fecha</label>
                            <input type="date" class="form-control mb-2 col-md-5" min="2010-01-01" name="Fecha"
                                id="FechaVer" required readOnly>
                            <label for="Importe">Importe</label>
                            <input type="text" step="0.01" maxlength="11" class="form-control" name="Importe"
                                id="ImporteVer" pattern="[0-9]{1,8}\.[0-9]{1,2}" title="12345678.99" required readOnly>
                            <label for="Descripcion">Descripcion</label>
                            <input type="text" maxlength="300" class="form-control mb-2" name="Descripcion"
                                id="DescripcionVer" required readOnly>
                        </div>
                    </div>
                    <div class="modal-footer">
                        {%if g.user and g.user.Id_tipousuario == 1 %}
                        <button type="submit" id="btn-save" class="btn btn-primary"
                            style="display: none;">Guardar</button>
                        <button type="button" id="btn-edit" class="btn btn-success btn-md" onclick="boton_editar()"
                            data-dismiss="modal">Editar</button>
                        {%endif%}
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                        <!-- #MODAL ON CLOSE $attr(disabled) ??? // CLOSE MODAL -->
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<script>
    $("#submitAdd").submit(() => {
        rubro = $("#Id_rubro").val()
        if (rubro == 'x') {
            $("#spanAdd").text("Seleccione un Rubro!").show().fadeOut(5000)
            event.preventDefault()
        }
    })

    $(function () { // Datetimepicker
        $('#datetimepicker1').datetimepicker({
            format: 'YYYY-MM-DD',
            minDate: moment('2000-01-01'),
            maxDate: moment(),
            icons: {
                previous: "fas fa-chevron-left",
                next: "fas fa-chevron-right",
            },
        });
        $('.input-group-append').click(function () {
            $('#datetimepicker1').trigger('focus');
        });
    });

    function boton_add() {
        $("#modelNuevo").clone().modal('show').on('hidden.bs.modal', function (e) { $(this).remove(); }); // Cierra el modal
    }

    function boton_editar() { // Modifica los atributos readOnly y Disabled del modal  #Ver
        $("#DescripcionVer").removeAttr("readOnly")
        $("#btn-save").removeAttr("style")
        $("#btn-edit").attr({ "style": "display: none;" })
        $("#modal_ver").clone().modal('show').on('hidden.bs.modal', function (e) { $(this).remove(); });
    }

    function boton_ver(id) { // Carga los datos desde la DB al html con los #id de los input
        $.ajax({
            url: '{{ url_for("cajas.egresos_modal_ver")}}',
            type: 'post',
            dataType: 'json',
            contentType: 'application/json',
            data: JSON.stringify([{
                "idEgreso": id,
            }]),
            success: function (data) {
                // console.log(data)
                if (data) {
                    $("#idEgresoVer").attr({ "value": data.Id })
                    $("#Id_RubroVer option").each(function () {
                        if (this.value == data.Id_rubro) {
                            $(this).attr('selected', 'selected')
                        }
                        else {
                            $(this).removeAttr('selected')
                        }
                    })
                    $("#FechaVer").attr({ "value": data.Fecha })
                    $("#ImporteVer").attr({ "value": data.Importe })
                    $("#DescripcionVer").attr({ "value": data.Descripcion })
                    $("#DescripcionVer").attr({ "readOnly": "readOnly" })
                    $("#btn-save").attr({ "style": "display: none;" })
                    $("#btn-edit").removeAttr("style")
                    $("#modal_ver").clone().modal('show').on('hidden.bs.modal', function (e) { $(this).remove(); });
                }
            }
        });
    }

    //Filtros columnas
    $(document).ready(function () {
        var table = $('#myTable').DataTable({
            "dom": 'Blfrtip',
            // "lengthMenu": [[12, 25, 50, -1], [12, 25, 50, "Todos"]],
            paging: false,
            lengthChange: false,
            pageLength: -1,
            orderCellsTop: true,
            scrollY: 525,
            scrollX: true,
            "order": [[1, "desc"]],
            "language": { "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json" },
            buttons: [
                {
                    extend: 'print',
                    text: '<i class="fa fa-print"> Imprimir</i>',
                    titleAttr: 'Imprimir',
                    className: 'btn btn-info',
                    exportOptions: {
                        columns: [0, 1, 2, 3]
                    },
                    customize: function (win) {
                        $(win.document.body).find('table')
                            .addClass('compact')
                            .removeClass('table-hover')
                            .css('font-size', 'inherit');
                    }
                },
                {
                    extend: 'pdfHtml5',
                    text: '<i class="fa fa-file-pdf"> PDF</i>',
                    titleAttr: 'Exportar a PDF',
                    className: 'btn btn-danger',
                    exportOptions: {
                        columns: [0, 1, 2, 3]
                    },
                }
            ]
        });
    });
</script>

{% endblock %}

mirageClub/app/cajas/templates/rubros.html
{% extends "base_template.html" %}

{% block title %}Rubros{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg">
        {%if g.user and g.user.Id_tipousuario == 1 %}
        <button type="button" class="btn btn-primary btn-lg" onclick="boton_add()">
            Cargar Nuevo Rubro
        </button>
        {%endif%}
    </div>
    <div class="col-md">
        <div class="btn-group float-right" role="group">
            <a class="btn btn-primary btn-lg mr-1 " href='{{ url_for("cajas.ingresos") }}'>
                Ingresos
                <!-- Cargar con MODAL?? // url for ruta ingresos: crear editar borrar-->
            </a>
            <a class="btn btn-primary btn-lg" href='{{ url_for("cajas.egresos") }}'>
                Egresos
                <!-- Cargar con MODAL?? // url for ruta egresos: crear editar borrar?? crear rubro-->
            </a>
        </div>
    </div>
</div>
<br>
<table style="width:100%" class="table table-dark table-hover table-bordered mt-3 display nowrap" id="myTable">
    <thead class="text-center">
        <th scope="col">Nombre</th>
        <th scope="col">Estado</th>
    </thead>
    <tbody>
        {%for rubro in rubros %}
        <tr class="text-center text-dark table-secondary">
            <td class="text-left" onclick="boton_ver({{rubro.Id}})">{{rubro.Nombre}}</td>
            {% if rubro.Eliminado == 1 %}
            <td onclick="boton_ver({{rubro.Id}})"> Activo </td>
            {% else %}
            <td onclick="boton_ver({{rubro.Id}})"> Eliminado </td>
            {%endif%}
            <!-- # MODAL BORRAR - CONFIRMACION ? -->
        </tr>
        {% endfor %}
    </tbody>
</table>


<!-- Modal AGREGAR-->
<div class="modal fade" id="modelNuevo" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-md modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    Nuevo Rubro
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="submitAdd" action='{{ url_for("cajas.rubros_add") }}' method="post">
                    <div class="card">
                        <div class="card-body">
                            <label for="Nombre">Nombre</label>
                            <input type="text" maxlength="200" class="form-control mb-2" name="Nombre"
                                placeholder="Nombre del Rubro" required>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-success" type="submit">
                            Guardar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<!-- Modal VER -->
<div class="modal fade" id="modal_ver" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-md modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Info</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- ID #?? // form.request['idActividad']-->
                <form id="submitVer" action='{{ url_for("cajas.rubros_edit") }}' method="post">
                    <!-- Recarga la pagina, AJAX? -->
                    <div class="card">
                        <div class="card-body">
                            <input type="text" name="idRubro" id="idRubroVer" style="display: none;">
                            <label for="Nombre">Nombre</label>
                            <input type="text" maxlength="200" class="form-control mb-2" name="Nombre" id="NombreVer"
                                required>
                            <label for="Estado">Estado</label>
                            <select type="text" class="form-control mb-2" name="Estado" id="EstadoVer" disabled
                                required>
                                <option value=1>Activo</option>
                                <option value=0>Eliminado</option>
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        {%if g.user and g.user.Id_tipousuario == 1 %}
                        <button type="submit" id="btn-save" class="btn btn-primary"
                            style="display: none;">Guardar</button>
                        <button type="button" id="btn-edit" class="btn btn-success btn-md" onclick="boton_editar()"
                            data-dismiss="modal">Editar</button>
                        {%endif%}
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<script>
    function boton_add() {
        $("#modelNuevo").clone().modal('show').on('hidden.bs.modal', function (e) { $(this).remove(); }); // Cierra el modal
    }

    function boton_editar() { // Modifica los atributos readOnly y Disabled del modal  #Ver
        $("#NombreVer").removeAttr("readOnly")
        $("#btn-save").removeAttr("style")
        $("#btn-edit").attr({ "style": "display: none;" })
        $("#modal_ver").clone().modal('show').on('hidden.bs.modal', function (e) { $(this).remove(); });
    }

    function boton_ver(id) { // Carga los datos desde la DB al html con los #id de los input
        $.ajax({
            url: '{{ url_for("cajas.rubros_modal_ver")}}',
            type: 'post',
            dataType: 'json',
            contentType: 'application/json',
            data: JSON.stringify([{
                "idRubro": id,
            }]),
            success: function (data) {
                // console.log(data)
                if (data) {
                    $("#idRubroVer").attr({ "value": data.Id })
                    $("#NombreVer").attr({ "value": data.Nombre })
                    $("#EstadoVer").val(Number(data.Eliminado))
                    $("#NombreVer").attr({ "readOnly": "readOnly" })
                    $("#btn-save").attr({ "style": "display: none;" })
                    $("#btn-edit").removeAttr("style")
                    $("#modal_ver").clone().modal('show').on('hidden.bs.modal', function (e) { $(this).remove(); });
                }
            }
        });
    }

    //Filtros columnas
    $(document).ready(function () {
        var table = $('#myTable').DataTable({
            "dom": 'Blfrtip',
            // "lengthMenu": [[12, 25, 50, -1], [12, 25, 50, "Todos"]],
            paging: false,
            lengthChange: false,
            pageLength: -1,
            orderCellsTop: true,
            scrollY: 525,
            scrollX: true,
            "language": { "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json" },
            buttons: [
                {
                    extend: 'print',
                    text: '<i class="fa fa-print"> Imprimir</i>',
                    titleAttr: 'Imprimir',
                    className: 'btn btn-info',
                    exportOptions: {
                        columns: [0]
                    },
                    customize: function (win) {
                        $(win.document.body).find('table')
                            .addClass('compact')
                            .removeClass('table-hover')
                            .css('font-size', 'inherit');
                    }
                },
                {
                    extend: 'pdfHtml5',
                    text: '<i class="fa fa-file-pdf"> PDF</i>',
                    titleAttr: 'Exportar a PDF',
                    className: 'btn btn-danger',
                    exportOptions: {
                        columns: [0]
                    },
                }
            ]
        });
    });
</script>

{% endblock %}